swagger: "2.0"
info: {}
paths: {}
definitions:
  models.BookMark:
    title: BookMark
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Name:
        type: string
