swagger: "2.0"
info: {}
basePath: /v1
paths:
  /bm/:
    get:
      tags:
      - bm
      description: get BookMark
      operationId: BookMarkController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.BookMark'
        "403":
          description: ""
    post:
      tags:
      - bm
      description: create BookMark
      operationId: BookMarkController.Post
      parameters:
      - in: body
        name: body
        description: body for BookMark content
        required: true
        schema:
          $ref: '#/definitions/models.BookMark'
      responses:
        "201":
          description: '{int} models.BookMark'
        "403":
          description: body is empty
  /bm/{id}:
    get:
      tags:
      - bm
      description: get BookMark by id
      operationId: BookMarkController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.BookMark'
        "403":
          description: :id is empty
    put:
      tags:
      - bm
      description: update the BookMark
      operationId: BookMarkController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for BookMark content
        required: true
        schema:
          $ref: '#/definitions/models.BookMark'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.BookMark'
        "403":
          description: :id is not int
    delete:
      tags:
      - bm
      description: delete the BookMark
      operationId: BookMarkController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.BookMark:
    title: BookMark
    type: object
    properties:
      Id:
        type: integer
        format: int64
      Name:
        type: string
tags:
- name: bm
  description: |2
     BookMarkController operations for BookMark
